require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - vendor/bundle/**/*
    - db/schema.rb
    - db/seeds.rb
    - db/seeds/*
    - db/migrate/*
    - gauge/*
    - Gemfile
Rails:
  Enabled: true
# Suppress all "Avoid using update_column because it skips validations." offenses.
Rails/SkipsModelValidations:
  Enabled: false
# Suppress all "Use find_by instead of dynamic find_by_user_and_uuid" offenses.
Rails/DynamicFindBy:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
Style/StringLiterals:
  EnforcedStyle: single_quotes
Layout/DotPosition:
  EnforcedStyle: trailing
  Enabled: true
Style/Documentation:
  Enabled: false
Style/PerlBackrefs:
  AutoCorrect: true
Style/NumericLiterals:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Metrics/BlockLength:
  Max: 120
Layout/LineLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: true
  Max: 15
Style/IfUnlessModifier:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Naming/PredicateName:
  Enabled: false
RSpec/EmptyExampleGroup:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: true
  Max: 15
Metrics/AbcSize:
  Enabled: false
Rails/UnknownEnv:
  Enabled: false
RSpec/ExpectInHook:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
