version: '3'
services:
  app:
    container_name: pdf-parsy
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/app/
      - pip:/usr/local/lib/python3.9/site-packages/
    environment:
      - PYTHONPATH=/app
      - S3_BUCKET=
      - S3_ACCESS_KEY_ID=
      - S3_SECRET_ACCESS_KEY=

volumes:
  pip:
