---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/pdf_to_text":
    parameters:
    - name: file
      in: formData
      type: file
      format: binary
      required: true
    post:
      summary: successful
      produces:
      - multipart/form-data
      consumes:
      - multipart/form-data
      tags:
      - PdfToText
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3003
