name: Continuous integration

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build base image
        run: docker-compose build

      - name: Install packages
        run: docker-compose run --rm app pip install -r requirements_dev.txt

      - name: Run tests
        run: docker-compose run --rm app python3 -m unittest test/**/*.py
