name: Continuous integration

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PIP_CACHE_DIR: /tmp/cache/pip
      PIP_CACHE_KEY: cache-pip
    steps:
      - uses: actions/checkout@v2

      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: ${{ runner.os }}-python-3.9.1-${{ env.PIP_CACHE_KEY }}-${{ hashFiles('requirements_dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.PIP_CACHE_KEY }}

      - name: Build base image
        run: docker-compose build

      - name: Install packages
        run: docker-compose run --rm app pip install -r requirements_dev.txt

      - name: Run tests
        run: docker-compose run --rm app python3 -m unittest test/*
